version: '3'

services:
  db:
    image: mdillon/postgis
    container_name: bdc_pg
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_PASSWORD=postgres
    volumes:
      - bdc_db:/var/lib/postgresql
    networks:
      - bdc

  sampledb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: brazildatacube/sampledb:1.0
    container_name: bdc_sample
    environment:
      - SQLALCHEMY_URI=postgresql://postgres:postgres@bdc_pg:5432/sampledb
    volumes:
      - /data:/data
    networks:
      - bdc

networks:
  bdc:
    driver: bridge

volumes:
  bdc_db: