version: '3'

services:
  sampledb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: registry.dpi.inpe.br/brazildatacube/sampledb:0.1.0
    container_name: bdc_sample
    ports:
      - 5001:5000
    environment:
      - SQLALCHEMY_URI=postgresql://localhost:5432/sampledb
      - CLIENT_AUDIENCE=samples
      - CLIENT_SECRET_KEY=CHANGE_ME