"""Change user table to oauth2

Revision ID: 891f82f24387
Revises: ea22133a5f12
Create Date: 2019-10-25 09:51:34.372668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891f82f24387'
down_revision = 'ea22133a5f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE bdc.observation DROP COLUMN user_id')
    op.execute('ALTER TABLE bdc.luc_classification_system DROP COLUMN user_id')
    op.execute('ALTER TABLE bdc.luc_class DROP COLUMN user_id')
    op.execute('ALTER TABLE bdc.observation ADD COLUMN user_id VARCHAR(50) NOT NULL')
    op.execute('ALTER TABLE bdc.luc_classification_system ADD COLUMN user_id VARCHAR(50) NOT NULL')
    op.execute('ALTER TABLE bdc.luc_class ADD COLUMN user_id VARCHAR(50) NOT NULL')
    op.execute('DROP TABLE bdc.users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='bdc'
    )
    op.execute('ALTER TABLE bdc.observation DROP COLUMN user_id')
    op.execute('ALTER TABLE bdc.luc_classification_system DROP COLUMN user_id')
    op.execute('ALTER TABLE bdc.luc_class DROP COLUMN user_id')
    op.execute('ALTER TABLE bdc.observation ADD COLUMN user_id INTEGER NOT NULL')
    op.execute('ALTER TABLE bdc.luc_classification_system ADD COLUMN user_id INTEGER NOT NULL')
    op.execute('ALTER TABLE bdc.luc_class ADD COLUMN user_id INTEGER NOT NULL')
    op.execute('ALTER TABLE bdc.observation ADD CONSTRAINT observation_user_id_fkey FOREIGN KEY (user_id) REFERENCES bdc.users(id)')
    op.execute('ALTER TABLE bdc.luc_classification_system ADD CONSTRAINT luc_classification_system_user_id_fkey FOREIGN KEY (user_id) REFERENCES bdc.users(id)')
    op.execute('ALTER TABLE bdc.luc_class ADD CONSTRAINT luc_class_user_id_fkey FOREIGN KEY (user_id) REFERENCES bdc.users(id)')
    # ### end Alembic commands ###
