"""add root tables

Revision ID: ea22133a5f12
Revises:
Create Date: 2019-06-26 09:50:57.401060

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = 'ea22133a5f12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA bdc')

    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='bdc'
    )
    op.create_table('luc_classification_system',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('authority_name', sa.Text(), nullable=False),
    sa.Column('system_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['bdc.users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='bdc'
    )
    op.create_table('luc_class',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('luc_classification_system_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['luc_classification_system_id'], ['bdc.luc_classification_system.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['parent_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['bdc.users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='bdc'
    )
    op.create_table('observation',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['bdc.luc_class.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['bdc.users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='bdc'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation', schema='bdc')
    op.drop_table('luc_class', schema='bdc')
    op.drop_table('luc_classification_system', schema='bdc')
    op.drop_table('users', schema='bdc')

    op.execute('DROP SCHEMA bdc')
    # ### end Alembic commands ###
