"""adding type ds

Revision ID: 43a97a4063c9
Revises: 9f4a4b16344f
Create Date: 2023-09-05 15:28:46.789211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import bdc_db
# revision identifiers, used by Alembic.
revision = '43a97a4063c9'
down_revision = '9f4a4b16344f'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    status_type = postgresql.ENUM('IN PROGRESS', 'PUBLISHED', 'IN REVISION', name='status_type')
    status_type.create(bind)

    op.add_column('datasets', sa.Column('users', sa.ARRAY(sa.Integer()), nullable=True), schema='sampledb')
    op.add_column('datasets', sa.Column('status', sa.ARRAY(sa.Enum('IN PROGRESS', 'PUBLISHED', 'IN REVISION', name='status_type')), nullable=False, server_default='{IN PROGRESS}'), schema='sampledb')
    op.add_column('datasets', sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='sampledb')
    op.alter_column('datasets', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='sampledb')
    op.drop_constraint('datasets_user_id_users_fkey', 'datasets', schema='sampledb', type_='foreignkey')
    op.create_foreign_key(op.f('datasets_user_id_users_fkey'), 'datasets', 'users', ['user_id'], ['user_id'], source_schema='sampledb', referent_schema='sampledb', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('datasets_user_id_users_fkey'), 'datasets', schema='sampledb', type_='foreignkey')
    op.create_foreign_key('datasets_user_id_users_fkey', 'datasets', 'users', ['user_id'], ['user_id'], source_schema='sampledb', referent_schema='sampledb')
    op.alter_column('datasets', 'metadata_json',
               existing_type=bdc_db.sqltypes.JSONB(astext_type=Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='sampledb')
    op.drop_column('datasets', 'properties', schema='sampledb')
    op.drop_column('datasets', 'status', schema='sampledb')
    op.drop_column('datasets', 'users', schema='sampledb')
    # ### end Alembic commands ###
