"""create sampledb.

Revision ID: 66e319ad1dc0
Revises: 
Create Date: 2020-03-30 17:13:04.289364

"""
from alembic import op
import sqlalchemy as sa

from lccs_db.models import LucClass, LucClassificationSystem


# revision identifiers, used by Alembic.
revision = '66e319ad1dc0'
down_revision = None
branch_labels = ('sample_db',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='sampledb'
    )
    op.create_table('datasets',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('classification_system_id', sa.Integer(), nullable=False),
    sa.Column('collect_method', sa.Enum('VISUAL', 'IN_LOCO', name='collectmethodenum'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('observation_table_name', sa.String(), nullable=False),
    sa.Column('midias_table_name', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['classification_system_id'], ['lccs.class_systems.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['user_id'], ['sampledb.users.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('id'),
    schema='sampledb'
    )
    op.create_table('provenance',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('dataset_parent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['sampledb.datasets.id'], ondelete='NO ACTION'),
    sa.ForeignKeyConstraint(['dataset_parent_id'], ['sampledb.datasets.id'], ondelete='NO ACTION'),
    sa.PrimaryKeyConstraint('dataset_id', 'dataset_parent_id'),
    schema='sampledb'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provenance', schema='sampledb')
    op.drop_table('datasets', schema='sampledb')
    op.drop_table('users', schema='sampledb')
    # ### end Alembic commands ###
