"""Review metadata.

Revision ID: 90f91c523f48
Revises: c36c83a0bf92
Create Date: 2022-01-04 10:25:35.213143

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import bdc_db

# from sample_db.schemas import metadata

# revision identifiers, used by Alembic.
revision = '90f91c523f48'
down_revision = 'c36c83a0bf92'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'metadata_json',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='sampledb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasets', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               schema='sampledb')
    # ### end Alembic commands ###
