"""updating type.

Revision ID: c36c83a0bf92
Revises: 
Create Date: 2021-09-17 13:58:51.702821

"""
from alembic import op
import sqlalchemy as sa

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sample_db.models import DatasetView


# revision identifiers, used by Alembic.
revision = 'c36c83a0bf92'
down_revision = 'bc8aee16d308'
branch_labels = ('sampledb',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_bind().connect() as conn:
        conn.execute('ALTER TYPE dataset_type ADD ATTRIBUTE created_at TIMESTAMP CASCADE;')
        conn.execute('ALTER TYPE dataset_type ADD ATTRIBUTE updated_at TIMESTAMP CASCADE;')

        conn.execute('COMMIT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_bind().connect() as conn:
        conn.execute('ALTER TYPE dataset_type DROP ATTRIBUTE created_at CASCADE;')
        conn.execute('ALTER TYPE dataset_type DROP ATTRIBUTE updated_at CASCADE;')

        conn.execute('COMMIT')

    # ### end Alembic commands ###
