"""add enum type

Revision ID: e6ed17b95ec0
Revises: 66e319ad1dc0
Create Date: 2020-04-02 15:54:48.865308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e6ed17b95ec0'
down_revision = '66e319ad1dc0'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect_method',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='sampledb'
    )
    op.add_column('datasets', sa.Column('collect_method_id', sa.Integer(), nullable=True), schema='sampledb')

    op.execute('ALTER TABLE sampledb.datasets ALTER COLUMN metadata_json TYPE JSON USING metadata_json::json')
    op.create_foreign_key(None, 'datasets', 'collect_method', ['collect_method_id'], ['id'], source_schema='sampledb', referent_schema='sampledb', ondelete='NO ACTION')
    op.drop_column('datasets', 'collect_method', schema='sampledb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('collect_method', postgresql.ENUM('VISUAL', 'IN_LOCO', name='collectmethodenum'), autoincrement=False, nullable=False), schema='sampledb')
    op.drop_constraint(None, 'datasets', schema='sampledb', type_='foreignkey')
    op.alter_column('datasets', 'metadata_json',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               schema='sampledb')
    op.drop_column('datasets', 'collect_method_id', schema='sampledb')
    op.drop_table('collect_method', schema='sampledb')
    # ### end Alembic commands ###
