"""add_index_review_0_2.

Revision ID: e988feb44852
Revises: 752b10fba4f9
Create Date: 2021-03-04 15:53:24.325865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e988feb44852'
down_revision = '752b10fba4f9'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collect_method', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='sampledb')
    op.create_index(op.f('idx_sampledb_collect_method_name'), 'collect_method', ['name'], unique=False, schema='sampledb')
    op.add_column('datasets', sa.Column('identifier', sa.String(), nullable=False), schema='sampledb')
    op.add_column('datasets', sa.Column('is_public', sa.Boolean(), nullable=False), schema='sampledb')
    op.alter_column('datasets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='sampledb')
    op.alter_column('datasets', 'version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='sampledb')
    op.create_unique_constraint(op.f('datasets_identifier_key'), 'datasets', ['identifier', 'version'], schema='sampledb')
    op.create_index('idx_datasets_start_date_end_date', 'datasets', ['start_date', 'end_date'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_classification_system_id'), 'datasets', ['classification_system_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_collect_method_id'), 'datasets', ['collect_method_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_identifier'), 'datasets', ['identifier'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_name'), 'datasets', ['name'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_start_date'), 'datasets', [sa.text('start_date DESC')], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_user_id'), 'datasets', ['user_id'], unique=False, schema='sampledb')
    op.drop_constraint('datasets_user_id_users_fkey', 'datasets', schema='sampledb', type_='foreignkey')
    op.drop_constraint('datasets_classification_system_id_class_systems_fkey', 'datasets', schema='sampledb', type_='foreignkey')
    op.drop_constraint('datasets_collect_method_id_collect_method_fkey', 'datasets', schema='sampledb', type_='foreignkey')
    op.create_foreign_key(op.f('datasets_classification_system_id_class_systems_fkey'), 'datasets', 'class_systems', ['classification_system_id'], ['id'],
                          source_schema='sampledb',
                          referent_schema='lccs',
                          onupdate='CASCADE',
                          ondelete='CASCADE')
    op.create_foreign_key(op.f('datasets_collect_method_id_collect_method_fkey'), 'datasets', 'collect_method', ['collect_method_id'], ['id'],
                          source_schema='sampledb',
                          referent_schema='sampledb',
                          onupdate='CASCADE',
                          ondelete='CASCADE')
    op.create_foreign_key(op.f('datasets_user_id_users_fkey'), 'datasets', 'users', ['user_id'], ['id'], source_schema='sampledb', referent_schema='sampledb', ondelete='CASCADE')
    op.create_index(op.f('idx_sampledb_provenance_dataset_id'), 'provenance', ['dataset_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_provenance_dataset_parent_id'), 'provenance', ['dataset_parent_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_users_email'), 'users', ['email'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_users_full_name'), 'users', ['full_name'], unique=False, schema='sampledb')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='sampledb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_email_key'), 'users', schema='sampledb', type_='unique')
    op.drop_index(op.f('idx_sampledb_users_full_name'), table_name='users', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_users_email'), table_name='users', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_provenance_dataset_parent_id'), table_name='provenance', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_provenance_dataset_id'), table_name='provenance', schema='sampledb')
    op.drop_constraint(op.f('datasets_user_id_users_fkey'), 'datasets', schema='sampledb', type_='foreignkey')
    op.drop_constraint(op.f('datasets_collect_method_id_collect_method_fkey'), 'datasets', schema='sampledb', type_='foreignkey')
    op.drop_constraint(op.f('datasets_classification_system_id_class_systems_fkey'), 'datasets', schema='sampledb', type_='foreignkey')
    op.create_foreign_key('datasets_collect_method_id_collect_method_fkey', 'datasets', 'collect_method', ['collect_method_id'], ['id'], source_schema='sampledb', referent_schema='sampledb')
    op.create_foreign_key('datasets_classification_system_id_class_systems_fkey', 'datasets', 'class_systems', ['classification_system_id'], ['id'], source_schema='sampledb', referent_schema='lccs')
    op.create_foreign_key('datasets_user_id_users_fkey', 'datasets', 'users', ['user_id'], ['id'], source_schema='sampledb', referent_schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_user_id'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_start_date'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_name'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_identifier'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_collect_method_id'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_classification_system_id'), table_name='datasets', schema='sampledb')
    op.drop_index('idx_datasets_start_date_end_date', table_name='datasets', schema='sampledb')
    op.drop_constraint(op.f('datasets_identifier_key'), 'datasets', schema='sampledb', type_='unique')
    op.alter_column('datasets', 'version',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='sampledb')
    op.alter_column('datasets', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='sampledb')
    op.drop_column('datasets', 'is_public', schema='sampledb')
    op.drop_column('datasets', 'identifier', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_collect_method_name'), table_name='collect_method', schema='sampledb')
    op.alter_column('collect_method', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='sampledb')
    # ### end Alembic commands ###

