"""add_index_review_0_2.

Revision ID: f50541dde5e5
Revises: 
Create Date: 2021-03-01 13:54:26.395947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50541dde5e5'
down_revision = None
branch_labels = ('sample-db',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_sampledb_collect_method_name'), 'collect_method', ['name'], unique=False, schema='sampledb')
    op.add_column('datasets', sa.Column('identifier', sa.String(), nullable=True), schema='sampledb')
    op.add_column('datasets', sa.Column('is_public', sa.Boolean(), nullable=False), schema='sampledb')
    op.create_index('idx_datasets_start_date_end_date', 'datasets', ['start_date', 'end_date'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_classification_system_id'), 'datasets', ['classification_system_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_collect_method_id'), 'datasets', ['collect_method_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_name'), 'datasets', ['name'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_start_date'), 'datasets', [sa.text('start_date DESC')], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_datasets_user_id'), 'datasets', ['user_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_provenance_dataset_id'), 'provenance', ['dataset_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_provenance_dataset_parent_id'), 'provenance', ['dataset_parent_id'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_users_email'), 'users', ['email'], unique=False, schema='sampledb')
    op.create_index(op.f('idx_sampledb_users_full_name'), 'users', ['full_name'], unique=False, schema='sampledb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_sampledb_users_full_name'), table_name='users', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_users_email'), table_name='users', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_provenance_dataset_parent_id'), table_name='provenance', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_provenance_dataset_id'), table_name='provenance', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_user_id'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_start_date'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_name'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_collect_method_id'), table_name='datasets', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_datasets_classification_system_id'), table_name='datasets', schema='sampledb')
    op.drop_index('idx_datasets_start_date_end_date', table_name='datasets', schema='sampledb')
    op.drop_column('datasets', 'is_public', schema='sampledb')
    op.drop_column('datasets', 'identifier', schema='sampledb')
    op.drop_index(op.f('idx_sampledb_collect_method_name'), table_name='collect_method', schema='sampledb')
    # ### end Alembic commands ###
